### ISSUE TITLE
virtual data

### ISSUE THREAD

**Issue by connormeaton** [YanWenqiang/HBLSTM-CRF#5]
On lines 234 and 235 you input the 'data' and 'labels', which you've referred to as virtual data. To train the model, I am assuming data should be a list of lists of utterances, and labels a list of list of DA labels from the swbd. Is this correct?

If so, should it look like this?:

data = [['hey how are you?', 'good, thanks', 'well whats next?'], ['this is an example', 'really?', 'yes']]
labels = [[1, 2, 1]. [3, 1, 2]]

and so on...

Thanks!
'

**Comment by YanWenqiang** [comment]
No. The paper uses a hierarchical algorithm.  the data should look like this:
data = [[["hey how are you?"], ["I am fine, and you?"], ["I am fine, too."]], [["My name is Jason, what's your name?"],["My name is Tina."],["Nice to meet you."],["Nice to meet you, too,"]]]
labels = [[1,2,3], [4,3,2,1]]

according to the paper, every utterance is given a label. So  the data shape must be [batch_size, num_of_utterance_in_dialogue, num_of_word_in_utterance]
the labels shape must be [batch_size, length_of_dialogue].

Maybe this will help you.

**Comment by YanWenqiang** [comment]
> On lines 234 and 235 you input the 'data' and 'labels', which you've referred to as virtual data. To train the model, I am assuming data should be a list of lists of utterances, and labels a list of list of DA labels from the swbd. Is this correct?
> 
> If so, should it look like this?:
> 
> data = [['hey how are you?', 'good, thanks', 'well whats next?'], ['this is an example', 'really?', 'yes']]
> labels = [[1, 2, 1]. [3, 1, 2]]
> 
> and so on...
> 
> Thanks!
> '

No. The paper uses a hierarchical algorithm. the data should look like this:
data = [[["hey how are you?"], ["I am fine, and you?"], ["I am fine, too."]], [["My name is Jason, what's your name?"],["My name is Tina."],["Nice to meet you."],["Nice to meet you, too,"]]]
labels = [[1,2,3], [4,3,2,1]]

according to the paper, every utterance is given a label. So the data shape must be [batch_size, num_of_utterance_in_dialogue, num_of_word_in_utterance]
the labels shape must be [batch_size, num_of_utterance_in_dialogue].

Maybe this will help you.

**Comment by connormeaton** [comment]
Thank you very much, this is very helpful.

I have been trying to run your code, but I keep running into this bug:

`Traceback (most recent call last):

  File "HBLSTM-CRF.py", line 308, in <module>
    main()
  File "HBLSTM-CRF.py", line 251, in main
    model = DAModel()
  File "HBLSTM-CRF.py", line 134, in __init__
    output = select(output, self.utterance_lengths) # [batch_size, dim]
  File "HBLSTM-CRF.py", line 82, in select
    idx = tf.stack([idx, length - 1], axis = 1)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1046, in stack
    return gen_array_ops.pack(values, axis=axis, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6971, in pack
    "Pack", values=values, axis=axis, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2027, in __init__
    control_input_ops)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 1 and 2
        From merging shape 0 with other shapes. for 'utterance_encoder/stack' (op: 'Pack') with input shapes: [?], [?,?].`

I haven't altered anything and and have not been able to find the issue. Have you experienced this? 

Thank you.

**Comment by adamelen** [comment]
> > On lines 234 and 235 you input the 'data' and 'labels', which you've referred to as virtual data. To train the model, I am assuming data should be a list of lists of utterances, and labels a list of list of DA labels from the swbd. Is this correct?
> > If so, should it look like this?:
> > data = [['hey how are you?', 'good, thanks', 'well whats next?'], ['this is an example', 'really?', 'yes']]
> > labels = [[1, 2, 1]. [3, 1, 2]]
> > and so on...
> > Thanks!
> > '
> 
> No. The paper uses a hierarchical algorithm. the data should look like this:
> data = [[["hey how are you?"], ["I am fine, and you?"], ["I am fine, too."]], [["My name is Jason, what's your name?"],["My name is Tina."],["Nice to meet you."],["Nice to meet you, too,"]]]
> labels = [[1,2,3], [4,3,2,1]]
> 
> according to the paper, every utterance is given a label. So the data shape must be [batch_size, num_of_utterance_in_dialogue, num_of_word_in_utterance]
> the labels shape must be [batch_size, num_of_utterance_in_dialogue].
> 
> Maybe this will help you.

Hello! Thanks for your code :)

The words must be somehow converted to integers? I suppose they can't be just strings, but also not one hot encodings because the tensor's dimension will change. So you assign them to labels [1,...,dictionary_size] ?

Thanks
